### ISSUE TITLE
Error when evaluating

### ISSUE THREAD

**Issue by CheungBH** [microsoft/multiview-human-pose-estimation-pytorch#40]
Hello. I am training 3d pose model with 
**python run/pose3d/estimate_cuda.py --cfg experiments-local/mixed/resnet50/256_fusion.yaml (GPU Version)**
, but I obtained an error:

**Traceback (most recent call last):
  File "/media/hkuit155/Windows/research/multiview-human-pose-estimation-pytorch/run/pose3d/estimate_cuda.py", line 120, in <module>
    main()
  File "/media/hkuit155/Windows/research/multiview-human-pose-estimation-pytorch/run/pose3d/estimate_cuda.py", line 64, in main
    all_heatmaps = h5py.File(prediction_path)['heatmaps']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/hkuit155/.local/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'heatmaps' doesn't exist)"**

I wonder how to fix it?

**Comment by CheungBH** [comment]
Also, I also wonder that whether the training code of 3d pose will be released?

**Comment by SevenMoGod** [comment]
I have the same problem, have you solved it?

**Comment by KungZell** [comment]
hello I  met the same problem , Has this problem been solved?
